### ISSUE TITLE
Need Clarification on Route and Controller Structure

### ISSUE THREAD

**Issue by AmirAK777** [lunarphp/livewire-starter-kit#87]
Hello, I've installed the starter kit, but I'm unsure how the routes and controllers work. In the HTTP controller folder, I don't see any classes. If, for example, I want to modify methods, how can I do that?

**Comment by tominal** [comment]
Hey @AmirAK777,
Since this is a Livewire project, the authors opted for a page / component design instead of a traditional MVC design like you're expecting. The page logic you're looking for is located in `app/Http/Livewire` with the `livewire:{name}` components you'll see located in `app/Http/Livewire/Components`
